[build]
  base = "client"
  publish = "dist"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
  publish = "client/dist"
